version: '3.8'

services:
  web:
    image: jupyter/base-notebook:latest
    container_name: jupyter
    ports:
      - "9998:8888"
    expose:
      - "9999"
    volumes:
      - jupyter_data:/home/jovyan/work
    networks:
      - jupyter-network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: promrazrab
      POSTGRES_PASSWORD: promrazrab
      POSTGRES_DB: promrazrab
    ports:
      - "6432:5432"
    expose:
      - "5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - jupyter-network

networks:
  jupyter-network:
    driver: bridge

volumes:
  jupyter_data:
  pg_data:
